service: apna-management

frameworkVersion: '3'

provider:
  name: aws
  region: ap-south-1
  runtime: provided.al2

  deploymentBucket:
    name: apna-management-serverless-${sls:stage}
    blockPublicAccess: true
    maxPreviousDeploymentArtifacts: 3
    
  environment:
    APP_ENV: ${sls:stage}
    APP_NAME: ${ssm:/apna/${sls:stage}/APP_NAME}
    APP_STORAGE: /tmp
    APP_KEY: ${ssm:/apna/${sls:stage}/APP_KEY}
    APP_DEBUG: ${ssm:/apna/${sls:stage}/APP_DEBUG}
    ASSET_URL: ${ssm:/apna/${sls:stage}/ASSET_URL}

    # App
    APP_LOCALE: en
    APP_FALLBACK_LOCALE: en
    APP_FAKER_LOCALE: en_US
    APP_MAINTENANCE_STORE: database
    BCRYPT_ROUNDS: 12

    # Logging
    LOG_CHANNEL: errorlog
    LOG_LEVEL: warning

    # Session
    SESSION_DRIVER: ${ssm:/apna/${sls:stage}/SESSION_DRIVER}
    SESSION_LIFETIME: 120
    SESSION_ENCRYPT: false
    SESSION_PATH: /
    SESSION_DOMAIN: null

    # Database
    DB_CONNECTION: ${ssm:/apna/${sls:stage}/DB_CONNECTION}
    DB_HOST: ${ssm:/apna/${sls:stage}/DB_HOST}
    DB_PORT: ${ssm:/apna/${sls:stage}/DB_PORT}
    DB_DATABASE: ${ssm:/apna/${sls:stage}/DB_DATABASE}
    DB_USERNAME: ${ssm:/apna/${sls:stage}/DB_USERNAME}
    DB_PASSWORD: ${ssm:/apna/${sls:stage}/DB_PASSWORD}

    # Cache / Queue
    CACHE_DRIVER: ${ssm:/apna/${sls:stage}/CACHE_DRIVER}
    DYNAMODB_CACHE_TABLE: ${ssm:/apna/${sls:stage}/DYNAMODB_CACHE_TABLE}
    QUEUE_CONNECTION: ${ssm:/apna/${sls:stage}/QUEUE_CONNECTION}
    SQS_PREFIX: ${ssm:/apna/${sls:stage}/SQS_PREFIX}
    SQS_QUEUE: ${ssm:/apna/${sls:stage}/SQS_QUEUE}

    # Mail
    MAIL_MAILER: ${ssm:/apna/${sls:stage}/MAIL_MAILER}
    MAIL_HOST: ${ssm:/apna/${sls:stage}/MAIL_HOST}
    MAIL_PORT: ${ssm:/apna/${sls:stage}/MAIL_PORT}
    MAIL_USERNAME: ${ssm:/apna/${sls:stage}/MAIL_USERNAME}
    MAIL_PASSWORD: ${ssm:/apna/${sls:stage}/MAIL_PASSWORD}
    MAIL_ENCRYPTION: ${ssm:/apna/${sls:stage}/MAIL_ENCRYPTION}
    MAIL_FROM_ADDRESS: ${ssm:/apna/${sls:stage}/MAIL_FROM_ADDRESS}
    MAIL_FROM_NAME: ${ssm:/apna/${sls:stage}/MAIL_FROM_NAME}

    # Filesystem / S3
    FILESYSTEM_DRIVER: ${ssm:/apna/${sls:stage}/FILESYSTEM_DRIVER}
    # AWS_ACCESS_KEY_ID: ${ssm:/apna/${sls:stage}/AWS_ACCESS_KEY_ID}
    # AWS_SECRET_ACCESS_KEY: ${ssm:/apna/${sls:stage}/AWS_SECRET_ACCESS_KEY}
    # AWS_DEFAULT_REGION: ${ssm:/apna/${sls:stage}/AWS_DEFAULT_REGION}
    AWS_BUCKET: ${ssm:/apna/${sls:stage}/AWS_BUCKET}
    AWS_URL: ${ssm:/apna/${sls:stage}/AWS_URL}

    #cashfree
    CASHFREE_BASE_URL: ${ssm:/apna/${sls:stage}/CASHFREE_BASE_URL}
    CASHFREE_CLIENT_ID: ${ssm:/apna/${sls:stage}/CASHFREE_CLIENT_ID}
    CASHFREE_CLIENT_SECRET: ${ssm:/apna/${sls:stage}/CASHFREE_CLIENT_SECRET}

    CASHFREE_PUBLIC_KEY: ${ssm:/apna/${sls:stage}/CASHFREE_PUBLIC_KEY}

plugins:
  - ./vendor/bref/bref

functions:
  web:
    handler: public/index.php
    timeout: 28
    role: LambdaExecutionRole
    layers:
      - ${bref:layer.php-82-fpm}
    events:
      - httpApi: '*'

  queue-worker:
    handler: artisan
    timeout: 60
    role: LambdaExecutionRole
    layers:
      - ${bref:layer.php-82}
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - SQSQueue
              - Arn
          batchSize: 1    

custom:
  roles:
    stage: apna-management-lambda-role
    prod: apna-management-prod-lambda-role

resources:
  Resources:
    LambdaExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        # RoleName: apna-management-lambda-role
        RoleName: ${self:custom.roles.${sls:stage}}
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
          - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
          - arn:aws:iam::aws:policy/AmazonS3FullAccess

        Policies:
          - PolicyName: SQSPermissions
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - sqs:SendMessage
                    - sqs:ReceiveMessage
                    - sqs:DeleteMessage
                    - sqs:GetQueueAttributes
                  Resource:
                    - arn:aws:sqs:ap-south-1:*:apna-queue-${sls:stage}  

    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: apna-queue-${sls:stage}      

    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: apna-cache-${sls:stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST    
